# Generated by Django 3.0.8 on 2020-08-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=2)),
                ('county', models.CharField(max_length=64)),
                ('population', models.IntegerField()),
                ('today_confirm', models.IntegerField()),
                ('today_death', models.IntegerField()),
                ('percent_confirm', models.DecimalField(decimal_places=3, max_digits=10)),
                ('percent_death', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
